spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:postgresql://localhost:5432/unicine-core
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        sql: debug

server:
  port: 8083