services:
  db:
    image: postgres
    container_name: unicine-core
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: unicine-core
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
