spring:
  application:
    name: boxoffice-service
  datasource:
    url: jdbc:postgresql://localhost:5432/unicine-core
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8089
